---
title: "Introduction to Relational Databases"
subtitle: "Computational Statistics<br>& Operations Research"
author: "<a href='htps://janusvm.github.io'>Janus Valberg-Madsen</a>"
date: "2019-03-18 @ Aalborg University"
output:
  xaringan::moon_reader:
    css: [default, "../assets/css/xaringan-css/janusvm.css", "../assets/css/xaringan-css/janusvm-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: none
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:10"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  echo = TRUE,
  fig.align = "center",
  fig.path = "input/figs/"
)
```

```{r intro, child = "input/01/intro.Rmd"}
```

---
layout: false
```{r why-dbs, child = "input/01/why-dbs.Rmd"}
```

---
layout: false
```{r sql, child = "input/01/sql.Rmd"}
```

---
layout: false

```{r exercises, child = "input/01/exercises.Rmd"}
```

---
layout: false

```{r postgres, child = "input/01/postgres.Rmd"}
```

---
layout: false
```{r links, child = "input/01/links.Rmd"}
```
