---
title: "Databases In R Using Tidyverse"
subtitle: "Computational Statistics<br>& Operations Research"
author: "<a href='htps://janusvm.github.io'>Janus Valberg-Madsen</a>"
date: "2019-04-01 @ Aalborg University"
output:
  xaringan::moon_reader:
    css: [default, "../assets/css/xaringan-css/janusvm.css", "../assets/css/xaringan-css/janusvm-fonts.css", "input/css/custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: none
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:10"
      beforeInit: "input/js/macros.js"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  fig.align = "center",
  fig.path = "input/figs/"
)
```

```{r intro, child = "input/03/intro.Rmd"}
```

---
layout: false

```{r dbi, child = "input/03/dbi.Rmd"}
```

---
layout: false

```{r dbi-exercises, child = "input/03/dbi-exercises.Rmd"}
```

---
layout: false

```{r tidyverse, child = "input/03/tidyverse.Rmd"}
```

---
layout: false

```{r tidyverse-sql, child = "input/03/tidyverse-sql.Rmd"}
```

---
layout: false

```{r notbooks, child = "input/03/notebooks.Rmd"}
```

---
layout: false

```{r tidyverse-exercises, child = "input/03/tidyverse-exercises.Rmd"}
```
