name: sql
class: center, middle, snowstorm

# SQL

???
So, in order to read or write to a database, we need to tell the server what we want.
This is what SQL is for.

---

# SQL

- Short for **Structured Query Language**
- A declarative, domain-specific language
- Used to communicate with the server
- Several implementations exist (we'll be using PostgreSQL)

???
- SQL was developed by IBM in the 1970's, initially called SEQUEL (Structured English Query Language), but the name later changed because "SEQUEL" was a trademark of another company
- Declarative, domain-specific:

    + Declarative: you write _what_ you want, rather than _how_ the program should do it (imperative)
    + Domain-specific: it's not a general programming language, but rather it deals with the domain of relational databases

- You type queries in this language into a client program, that executes them on the server
- Other examples include: MySQL, MS SQL Server, SQLite, and Oracle; the choice of PostgreSQL is based on it being cross platform, open source, and standard compliant

---

# Basic syntax: selection

???
Most commonly, you'll be querying the database to _read_ data from a table;
this is done with a `SELECT` statement.

--

```sql
SELECT col1, col2, ... FROM table1;
```

"**SELECT** all rows of columns `col1`, `col2`, etc. **FROM** the table named `table1`"

???
The syntax reads much like plain English;
you say which columns you want to `SELECT` (retrieve) and `FROM` which table.

--

```sql
SELECT * FROM table1;
```

"**SELECT** all rows of all columns **FROM** the table `table1`"

???
The `*` in the column list is shorthand for all columns.

---
layout: true
# Basic syntax: filtering

---

???
Oftentimes, you don't want _all_ the rows in a table, but only a subset.
This is called _filtering_.

--

```sql
SELECT * FROM table1
 WHERE <condition>;
```

"**SELECT** the rows **FROM** `table1` **WHERE** `condition` is true"

???
The `WHERE` keyword is used to filter rows conditionally.
Here, `condition` is any statement that evaluates to a boolean value (`true/false`)

--

```sql
SELECT DISTINCT * FROM table1;
```

"**SELECT** **DISTINCT** (unique) rows **FROM** `table1`"

???
The `DISTINCT` keyword signifies that you don't want duplicate rows; only unique combinations of the values in the selected columns are retrieved.

---

### Boolean expressions

Common functions in such `condition`s:

.pull-left[
- Equality (NB: not assignment): `col = val`
- Inequality: `>`, `<`, `>=`, `<=`
- Double inequality: `col BETWEEN a AND b`
- Set membership: `col IN (a, b, ...)`
]

.pull-right[
- String mathching: `col LIKE pattern`

  → Wildcards: `_` for single char, `%` for many

- Logical operators: `AND`, `OR`, `NOT`
]
